/* ===== Pharmacy OS screens (design sketches, sample data). Each returns HTML for a .s canvas that scales with its container.
   The product's own look: grey canvas, white cards, black pills, large type. Indigo = chosen or done, amber = soon, red pen = stop. ===== */
const KI = id => `<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#k-${id}"/></svg>`;
const TK = on => `<i class="s__tk${on ? ' on' : ''}">${on ? '<svg viewBox="0 0 16 16" aria-hidden="true"><use href="#i-check"/></svg>' : ''}</i>`;
const STORE = 'Ananya Medicals', DIST = 'Krishna Pharma Agencies';
const MED = [
  ['Paracetamol 650 mg', 'Strip of 15', 20, 'PK2291', '08/2028', 18.4],
  ['Amoxicillin 500 mg', 'Strip of 10', 10, 'AX7730', '03/2028', 62.1],
  ['Metformin 500 mg SR', 'Strip of 15', 15, 'MF1184', '11/2027', 24.9],
  ['Telmisartan 40 mg', 'Strip of 15', 12, 'TL5521', '06/2028', 71.5],
  ['Pantoprazole 40 mg', 'Strip of 15', 10, 'PZ0917', '01/2028', 58.0],
  ['Cetirizine 10 mg', 'Strip of 10', 10, 'CT3340', '02/2027', 11.2]
];
const NAV = [['list', 'Order'], ['ticks', 'Receive'], ['box', 'Stock'], ['receipt', 'Bill'], ['users', 'Customers'], ['chart', 'Reports']];
const BAR = () => `<div class="s__bar"><svg class="s__cap" viewBox="0 0 80 80" aria-hidden="true"><use href="#i-capsule"/></svg><b>${STORE}</b><span class="s__find">${KI('search')}Search a medicine, a bill or a customer</span><span class="s__tool">A<small>A</small></span><span class="s__tool is--te">తె</span></div>`;
const APP = (on, body) => `${BAR()}<div class="s__body"><div class="s__nav">${NAV.map(([ic, t], i) => `<span class="${i === on ? 'on' : ''}">${KI(ic)}${t}</span>`).join('')}</div><div class="s__main">${body}</div></div>`;
const HD = (t, right = '') => `<div class="s__hd"><span class="s__t">${t}</span><span class="s__hdr">${right}</span></div>`;
const CH = (t, c = '') => `<span class="s__chip ${c}">${t}</span>`;
const BTN = (t, c = '') => `<span class="s__btn ${c}">${t}</span>`;
const QTY = n => `<span class="s__qty"><i>−</i><b>${n}</b><i>+</i></span>`;
/* A list screen: title, chips, column template, header cells, rows of cells, optional side card */
const LIST = (on, title, chips, cols, head, rows, foot = '') => APP(on, `${HD(title, chips)}<div class="s__card s__tbl" style="--cols:${cols}"><div class="s__tr is--h">${head.map(h => `<span>${h}</span>`).join('')}</div>${rows.map(r => `<div class="s__tr${r.c ? ' ' + r.c : ''}">${(r.v || r).map(c => `<span>${c}</span>`).join('')}</div>`).join('')}</div>${foot}`);
const BAD = t => `<em class="s__bad">${KI('alert')}${t}</em>`;
const WARN = t => `<em class="s__warn">${KI('clock')}${t}</em>`;
const OK = t => `<em class="s__ok">${t}</em>`;
/* Phone parts */
const PHONE = inner => `<div class="sph"><div class="sph__scr">${inner}</div></div>`;
const CHAT = (name, sub, msgs) => `<div class="swa"><div class="swa__hd">${KI('back')}<i class="swa__av">${name[0]}</i><div><b>${name}</b><small>${sub}</small></div></div><div class="swa__body">${msgs.join('')}</div><div class="swa__in"><span>Message</span>${KI('send')}</div></div>`;
const OUT = (h, extra = '') => `<div class="swa__m is--out">${h}${extra}<small>10:42 ✓✓</small></div>`;
const INC = h => `<div class="swa__m">${h}<small>11:05</small></div>`;
const DOC = (t, s) => `<div class="swa__doc">${KI('file')}<div><b>${t}</b><small>${s}</small></div></div>`;
const LINK = t => `<span class="swa__link">${KI('link')}${t}</span>`;
const DUO = (phone, title, steps) => `<div class="s__duo">${phone}<div class="s__side"><span class="s__t">${title}</span><ul class="s__steps">${steps.map(([a, b, c]) => `<li class="${c || ''}"><i></i><div><b>${a}</b><small>${b}</small></div></li>`).join('')}</ul></div></div>`;
const WA_ORDER = CHAT(DIST, 'Distributor', [OUT(`<b>Order 1042</b> from ${STORE}<br>6 items, about ₹3,060`, DOC('Order-1042.pdf', '1 page') + LINK('Open the order')), INC('5 available.<br>Pantoprazole: only 6.')]);
const WA_BILL = CHAT(STORE, 'Business account', [`<div class="swa__m">Thank you, Lakshmi garu.<br><b>Bill 2281 · ₹486</b><br>3 items${LINK('View your bill')}<small>6:14 pm</small></div>`]);
const WA_REMIND = CHAT(STORE, 'Business account', ['<div class="swa__m">Your regular medicines may be running low. Reply <b>YES</b> and we will keep them ready.<small>9:00 am</small></div>', '<div class="swa__m is--out">YES<small>9:12 am ✓✓</small></div>', '<div class="swa__m">Packed. Ready from 11 am.<small>9:13 am</small></div>']);
const OWNER = `<div class="sow"><div class="sow__hd"><div><small>Today · All stores</small><b>₹48,260</b></div><span class="sow__up">Up 8% on last Thursday</span></div><div class="sow__two"><div><small>Cash</small><b>₹18,400</b></div><div><small>UPI</small><b>₹29,860</b></div></div><div class="sow__box"><span class="sow__lbl">Needs you <i>3</i></span><ul><li>${KI('list')}<div><b>Approve an order</b><small>Store 2 · ₹62,000</small></div>${KI('chev')}</li><li>${KI('clock')}<div><b>9 items expire soon</b><small>₹3,140 at risk</small></div>${KI('chev')}</li><li>${KI('rupee')}<div><b>Pay ${DIST.split(' ')[0]} Pharma</b><small>₹18,200 due tomorrow</small></div>${KI('chev')}</li></ul></div><div class="sow__nav"><span class="on">${KI('home')}Today</span><span>${KI('store')}Stores</span><span>${KI('receipt')}Bills</span><span>${KI('bell')}Alerts</span></div></div>`;
const NEEDS = `<div class="sow"><div class="sow__hd"><div><small>Store 2 · Order 1057</small><b>₹62,000</b></div><span class="sow__up is--amber">Above your ₹50,000 limit</span></div><div class="sow__box"><span class="sow__lbl">What is in it</span><ul><li>${KI('pill')}<div><b>42 items</b><small>31 are low or out</small></div></li><li>${KI('truck')}<div><b>${DIST}</b><small>Usual distributor</small></div></li><li>${KI('user')}<div><b>Asked by Imran</b><small>Counter, 4:12 pm</small></div></li></ul></div><div class="sow__act"><span class="s__btn">Approve</span><span class="s__btn is--ghost">Open the list</span></div><div class="sow__nav"><span>${KI('home')}Today</span><span>${KI('store')}Stores</span><span>${KI('receipt')}Bills</span><span class="on">${KI('bell')}Alerts</span></div></div>`;
const DLINK = `<div class="sdl"><div class="sdl__url">${KI('lock')}Order link · opens in the browser</div><div class="sdl__hd"><small>Order 1042 from</small><b>${STORE}</b><small>6 items · no login needed</small></div><ul class="sdl__list">${MED.map((m, i) => `<li><div><b>${m[0]}</b><small>${m[2]} × ${m[1].toLowerCase()}</small></div>${i === 4 ? '<span class="sdl__pill is--short">Only 6</span>' : '<span class="sdl__pill">Available</span>'}</li>`).join('')}</ul><div class="sdl__act"><span class="s__btn">Send reply</span><span class="s__btn is--ghost">${KI('clip')}Attach bill</span></div></div>`;

const V = {
  order: () => APP(0, `${HD('To order', CH(DIST + ' ▾'))}
    <div class="s__search">${KI('search')}<b>par</b><i class="s__caret"></i><span>Type a medicine</span></div>
    <div class="s__drop"><small>From your history</small>
      <div class="s__opt on"><div><b>Paracetamol 650 mg</b><span>Strip of 15</span></div><em>You have 4 · you usually order 20</em></div>
      <div class="s__opt"><div><b>Paracetamol 500 mg</b><span>Strip of 10</span></div><em>You have 22</em></div>
      <div class="s__opt is--new"><div>${KI('plus')}<b>Add “par…” as a new medicine</b></div><em>Saved for next time</em></div>
    </div>
    <div class="s__card s__tbl" style="--cols:1fr 6.4em 4.6em"><div class="s__tr"><span><b>Amoxicillin 500 mg</b><small>Strip of 10 · low</small></span><span>${QTY(10)}</span><span>₹621</span></div><div class="s__tr"><span><b>Metformin 500 mg SR</b><small>Strip of 15 · low</small></span><span>${QTY(15)}</span><span>₹374</span></div></div>
    <div class="s__foot"><span><b>6 items</b> · about ₹3,060</span>${BTN('Send order')}</div>`),

  send: () => DUO(PHONE(WA_ORDER), 'Order 1042', [['Sent on WhatsApp', '10:42 am, with a PDF and a link', 'on'], ['Opened', '10:44 am, no login', 'on'], ['Confirmed', '11:05 am, 5 of 6 available', 'on'], ['Arriving', 'Today, with the bill', '']]),

  check: () => APP(1, `${HD('Receive · Order 1042', CH(DIST) + CH('Bill KP/3391'))}
    <div class="s__card s__tbl is--chk" style="--cols:2.3em 1fr 5em 5.4em 5.2em">${MED.map((m, i) => `<div class="s__tr${i === 4 ? ' is--bad' : i === 5 ? ' is--warn' : ''}"><span>${TK(i < 4)}</span><span><b>${m[0]}</b><small>${m[1]}</small></span><span>${i === 4 ? BAD('6 of 10') : `<b>${m[2]}</b> of ${m[2]}`}</span><span class="s__mono">${m[3]}</span><span>${i === 5 ? WARN('02/2027') : `<span class="s__mono">${m[4]}</span>`}</span></div>`).join('')}</div>
    <div class="s__foot"><span><b>4 ticked</b> · 1 short · 1 expires soon</span><span class="s__row">${BTN(KI('qr') + 'Scan pack', 'is--ghost')}${BTN('Add to stock')}</span></div>`),

  stock: () => APP(2, `${HD('Stock', CH('All', 'on') + CH('Low · 12') + CH('Expiring · 9') + CH('Fridge · 4'))}
    <div class="s__split"><div class="s__card s__tbl" style="--cols:1fr 2.6em 3.4em 5.2em"><div class="s__tr is--h"><span>Medicine</span><span>Shelf</span><span>Have</span><span>Expiry</span></div>${[[0, 'A2', 24], [1, 'B1', 14], [2, 'B3', 19], [3, 'C1', 15], [5, 'A4', 12]].map(([k, sh, q]) => `<div class="s__tr"><span><b>${MED[k][0]}</b><small>Batch ${MED[k][3]}</small></span><span class="s__mono">${sh}</span><span><b>${q}</b></span><span>${k === 5 ? WARN('02/2027') : `<span class="s__mono">${MED[k][4]}</span>`}</span></div>`).join('')}</div>
    <div class="s__card s__just"><small>Just added</small><b>6 items</b><span>from order 1042</span><ul><li>${OK('✓')} Stock up, by batch</li><li>${OK('✓')} Expiry alerts set</li><li>${OK('✓')} ₹2,815 due on 7 Nov</li></ul></div></div>`),

  sell: () => APP(3, `${HD('New bill', CH('Lakshmi · 98765 •••43') + CH('Counter 1'))}
    <div class="s__split is--bill"><div class="s__col"><div class="s__search is--sm">${KI('search')}<b>tel</b><i class="s__caret"></i></div>
      <div class="s__card s__tbl" style="--cols:1fr 5.6em 3.6em">${[[3, 1, 71.5, 'H'], [2, 2, 49.8, 'H'], [0, 1, 18.4, '']].map(([k, q, p, sc]) => `<div class="s__tr"><span><b>${MED[k][0]}</b><small>${MED[k][1]}${sc ? ' · <i class="s__rx">Rx</i>' : ''} · oldest batch</small></span><span>${QTY(q)}</span><span><b>₹${p}</b></span></div>`).join('')}</div>
      <span class="s__hint">${KI('shield')}Expired stock cannot be added to a bill</span></div>
    <div class="s__card s__pay"><small>To pay</small><b class="s__total">₹486</b><span>3 items · GST inside</span><div class="s__ways"><span class="on">UPI</span><span>Cash</span><span>Card</span></div>${BTN('Print + WhatsApp')}</div></div>`),

  wabill: () => DUO(PHONE(WA_BILL), 'Bill 2281', [['Bill sent as a link', 'No drug names in the message', 'on'], ['Customer saved', 'Lakshmi, 4th visit', 'on'], ['H1 register', '1 line added by itself', 'on'], ['Refill reminder', 'Set for 4 November', 'on']]),
  remind: () => DUO(PHONE(WA_REMIND), 'Refill due', [['30 tablets, one a day', 'Billed on 8 October', 'on'], ['Reminder sent', 'Day 27, at 9 am', 'on'], ['She replied YES', 'Order in the store inbox', 'on'], ['Packed', 'Ready at 11 am', 'on']]),
  owner: () => `<div class="s__duo is--own">${PHONE(OWNER)}<div class="s__side"><span class="s__t">All stores, today</span><ul class="s__bars">${[['Store 1 · Main road', 62, '₹21,400'], ['Store 2 · Bus stand', 100, '₹18,960'], ['Store 3 · Hospital gate', 41, '₹7,900']].map(([n, w, v], i) => `<li><span>${n}</span><i style="--w:${[100, 88, 37][i]}%"></i><b>${v}</b></li>`).join('')}</ul><span class="s__hint">${KI('eye')}Every bill appears here as it is made</span></div></div>`,

  dues: () => LIST(5, 'Pay distributors', CH('Due this week · 3', 'on') + CH('All'), '1fr 4.6em 5.6em 5em', ['Distributor', 'Bills', 'Amount', 'Due'], [[`<b>${DIST}</b>`, '2', '<b>₹18,200</b>', WARN('Tomorrow')], ['<b>Godavari Distributors</b>', '1', '<b>₹9,640</b>', '<span class="s__mono">12 Oct</span>'], ['<b>Sri Venkat Pharma</b>', '3', '<b>₹31,075</b>', '<span class="s__mono">15 Oct</span>']], `<div class="s__foot"><span>Reminder goes three days before each date</span>${BTN('Pay ₹18,200')}</div>`),
  returns: () => LIST(2, 'Expiry returns', CH('Open · 4', 'on') + CH('Credited'), '1fr 4.4em 5.4em 6.8em', ['To', 'Items', 'Value', 'Status'], [[`<b>${DIST}</b>`, '7', '₹2,310', WARN('Sent 12 days ago')], ['<b>Godavari Distributors</b>', '3', '₹890', OK('Credit note in')], ['<b>Sri Venkat Pharma</b>', '5', '₹1,640', BAD('No reply, 40 days')]], `<div class="s__foot"><span>Each return is tracked until the credit note arrives</span>${BTN('Remind all', 'is--ghost')}</div>`),
  expiry: () => LIST(5, 'Expiring in 60 days', CH('60 days', 'on') + CH('90 days') + CH('Dead stock'), '1fr 3.2em 5.2em 4.6em', ['Medicine', 'Have', 'Expires', 'Value'], [[`<b>${MED[5][0]}</b><small>${DIST}</small>`, '12', BAD('18 days'), '₹134'], ['<b>Azithromycin 500 mg</b><small>Godavari Distributors</small>', '8', WARN('41 days'), '₹968'], ['<b>ORS sachet</b><small>Sri Venkat Pharma</small>', '30', WARN('52 days'), '₹540'], ['<b>Vitamin D3 60K</b><small>Krishna Pharma Agencies</small>', '6', WARN('58 days'), '₹498']], `<div class="s__foot"><span><b>₹3,140</b> at risk in 9 items</span><span class="s__row">${BTN('Download', 'is--ghost')}${BTN('Return to distributor')}</span></div>`),
  lowstock: () => LIST(5, 'Running low', CH('Below reorder · 12', 'on') + CH('Out · 3'), '1fr 3.6em 4.8em 5.4em', ['Medicine', 'Have', 'Sells a week', 'Order'], [[`<b>${MED[0][0]}</b>`, BAD('4'), '18', QTY(20)], [`<b>${MED[4][0]}</b>`, BAD('3'), '9', QTY(10)], [`<b>${MED[1][0]}</b>`, WARN('6'), '8', QTY(10)], [`<b>${MED[2][0]}</b>`, WARN('7'), '11', QTY(15)]], `<div class="s__foot"><span>Sent to your phone every morning</span>${BTN('Add all to order')}</div>`),
  campaign: () => APP(4, `${HD('New offer', CH('Step 2 of 3'))}<div class="s__split is--bill"><div class="s__col"><div class="s__card"><small>Who gets it</small><div class="s__pickrow">${CH('Sugar and BP regulars · 214', 'on')}${CH('Bought baby care · 96')}${CH('Not seen in 60 days · 140')}</div></div><div class="s__card"><small>The message</small><p class="s__msg">Free sugar check this Sunday, 8 to 11 am, at ${STORE}. Reply STOP to end.</p><span class="s__hint">${KI('shield')}No medicine names. Checked.</span></div></div><div class="s__card s__pay"><small>Cost</small><b class="s__total">₹218</b><span>214 people · ₹1.02 each with GST</span>${BTN('Send on WhatsApp')}</div></div>`),
  customer: () => LIST(4, 'Lakshmi', CH('98765 •••43') + CH('Said yes to messages', 'on'), '1fr 4.4em 4.4em 5.4em', ['Regular medicine', 'Dose', 'Lasts', 'Refill'], [[`<b>${MED[3][0]}</b><small>Dr. Rao</small>`, '1 a day', '15 days', WARN('In 3 days')], [`<b>${MED[2][0]}</b><small>Dr. Rao</small>`, '2 a day', '15 days', '<span class="s__mono">19 Oct</span>'], ['<b>Vitamin D3 60K</b>', '1 a week', '4 weeks', '<span class="s__mono">2 Nov</span>']], `<div class="s__foot"><span>4 visits · ₹1,930 this year · nothing due</span>${BTN('New bill')}</div>`),
  accounts: () => APP(5, `${HD('Day book · Today', CH('Today', 'on') + CH('This month'))}<div class="s__kpis"><div><small>Sales</small><b>₹21,400</b></div><div><small>Profit</small><b>₹4,180</b></div><div><small>Cash in drawer</small><b>₹8,250</b></div><div><small>To collect</small><b>₹2,960</b></div></div><div class="s__card s__tbl" style="--cols:1fr 5em 5em"><div class="s__tr is--h"><span>Entry</span><span>In</span><span>Out</span></div><div class="s__tr"><span><b>62 bills</b><small>UPI ₹13,150 · Cash ₹8,250</small></span><span><b>₹21,400</b></span><span></span></div><div class="s__tr"><span><b>${DIST}</b><small>Paid by bank</small></span><span></span><span>₹12,000</span></div><div class="s__tr"><span><b>Shop expenses</b><small>Tea, courier</small></span><span></span><span>₹260</span></div></div>`),
  gst: () => LIST(5, 'GST · September', CH('GSTR-1') + CH('GSTR-3B', 'on') + CH('Tally file'), '1fr 5.4em 5em 5em', ['Rate', 'Sales', 'Tax out', 'Tax in'], [['<b>5%</b><small>Most medicines</small>', '₹5,12,300', '₹24,395', '₹21,880'], ['<b>Nil</b><small>Listed life-saving drugs</small>', '₹18,640', '—', '—'], ['<b>18%</b><small>Other items</small>', '₹41,200', '₹6,285', '₹5,410']], `<div class="s__foot"><span>Your CA has a read-only login</span><span class="s__row">${BTN(KI('download') + 'Excel', 'is--ghost')}${BTN('Send to CA')}</span></div>`),
  h1: () => LIST(5, 'Schedule H1 register', CH('October', 'on') + CH('Inspection pack'), '4.2em 1fr 1fr 3em', ['Date', 'Patient · Doctor', 'Medicine', 'Qty'], [['<span class="s__mono">08 Oct</span>', '<b>Lakshmi</b><small>Dr. Rao</small>', 'Levofloxacin 500 mg', '5'], ['<span class="s__mono">08 Oct</span>', '<b>Suresh</b><small>Dr. Fatima</small>', 'Cefixime 200 mg', '10'], ['<span class="s__mono">07 Oct</span>', '<b>Anitha</b><small>Dr. Rao</small>', 'Alprazolam 0.25 mg', '10']], `<div class="s__foot"><span>${OK('✓')} Filled from the bill. Kept for three years.</span>${BTN(KI('download') + 'Download')}</div>`),
  one: () => APP(5, `${HD('Today', CH(STORE, 'on'))}<div class="s__kpis"><div><small>Sales</small><b>₹21,400</b></div><div><small>Profit</small><b>₹4,180</b></div><div><small>Bills</small><b>62</b></div><div><small>Cash + UPI</small><b>₹21,400</b></div></div><div class="s__card s__need"><small>Needs you today</small><ul><li>${WARN('9')}<b>items expire within 60 days</b><span>₹3,140</span></li><li>${BAD('12')}<b>items below reorder level</b><span>Order ready</span></li><li>${WARN('1')}<b>distributor to pay tomorrow</b><span>₹18,200</span></li></ul></div>`),
  multi: () => LIST(5, 'Stores at a glance', CH('All stores', 'on') + CH('Today'), '1fr 5em 3.6em 3em 4.4em', ['Store', 'Sales', 'Margin', 'Low', 'Expiring'], [['<b>Main road</b>', '<b>₹21,400</b>', '19%', '12', WARN('9')], ['<b>Bus stand</b>', '<b>₹18,960</b>', '21%', '7', '4'], ['<b>Hospital gate</b>', '<b>₹7,900</b>', '17%', BAD('23'), WARN('11')], ['<b>Warehouse</b>', '—', '—', '3', '2']], `<div class="s__foot"><span>${WARN('1')} order waits for you · ${BAD('1')} transfer does not match</span>${BTN('Move stock')}</div>`),

  /* Our drawing of the layout common to desktop billing tools. Not a screenshot of any product. */
  legacy: () => `<div class="so__title"><span>PURCHASE ENTRY - [COMPANY 2026-27]</span><i>_ ☐ ✕</i></div><div class="so__menu">${['Masters', 'Transactions', 'Display', 'Reports', 'GST', 'Utilities', 'Tools', 'Window', 'Help'].map(m => `<span>${m}</span>`).join('')}</div>
    <div class="so__form">${[['Party', 'KRISHNA PHARMA AGENCIES'], ['Bill No', 'KP/3391'], ['Date', '08-10-2026'], ['Type', 'CREDIT'], ['Due', '07-11-2026'], ['GSTIN', '37AAAAA0000A1Z5']].map(([k, v]) => `<label>${k}<b>${v}</b></label>`).join('')}</div>
    <div class="so__grid"><div class="so__r is--h">${['Sr', 'Item Name', 'Pack', 'Batch', 'Exp', 'Qty', 'Free', 'P.Rate', 'Dis%', 'MRP', 'GST%', 'Amount'].map(h => `<span>${h}</span>`).join('')}</div>${MED.map((m, i) => `<div class="so__r${i === 4 ? ' is--sel' : ''}"><span>${i + 1}</span><span>${m[0].toUpperCase()}</span><span>${m[1].replace('Strip of ', '1*')}</span><span>${i < 4 ? m[3] : ''}</span><span>${i < 4 ? m[4].replace('/20', '/') : ''}</span><span>${i < 4 ? m[2] : ''}</span><span>${i < 4 ? '0' : ''}</span><span>${i < 4 ? m[5].toFixed(2) : ''}</span><span>${i < 4 ? '0.00' : ''}</span><span>${i < 4 ? (m[5] * 1.28).toFixed(2) : ''}</span><span>${i < 4 ? '5' : ''}</span><span>${i < 4 ? (m[5] * m[2]).toFixed(2) : ''}</span></div>`).join('')}${Array.from({ length: 5 }, () => `<div class="so__r">${'<span></span>'.repeat(12)}</div>`).join('')}</div>
    <div class="so__sum"><span>Items: 4/6</span><span>Gross: 2,225.10</span><span>Disc: 0.00</span><span>GST: 111.26</span><b>Net: 2,336.36</b></div>
    <div class="so__keys">${['F2-New', 'F3-Edit', 'F4-Party', 'F5-Batch', 'F6-Item', 'F7-Scheme', 'F8-Delete', 'F9-Save', 'F10-Print', 'Esc-Exit'].map(k => `<span>${k}</span>`).join('')}</div>`,

  /* Phone-only canvases */
  dlink: () => DLINK,
  wabillm: () => WA_BILL,
  remindm: () => WA_REMIND,
  ownerm: () => OWNER,
  needsm: () => NEEDS
};
