"""Short-form content shared by the client pitch and the team playbook.

One source of truth: the pitch renders the client fields, the playbook renders the
team fields and seeds its shared library from the rest.
"""

PHASES = [
    {
        "id": "connect", "n": "00", "name": "Connect", "tag": "Find the fit",
        "short": "One call. A clear plan.",
        "intro": "We learn your business. You see if we fit.",
        "do": ["A 45-min discovery call", "Quick review of your site and rivals", "What to build now. What can wait."],
        "get": ["Call recap", "Proposal: scope, phases, timeline"],
        "need": ["45 minutes", "Links: site, socials, brand files"],
        "gate": "You accept the proposal",
        "vis": "call",
        "team": {
            "purpose": "Qualify the lead. Win a clear yes.",
            "steps": [
                "Research the lead: site, socials, reviews, 3 rivals",
                "Send the questionnaire 24 h before the call",
                "Run the call from the question list. Record with consent",
                "Log the lead and notes in Notion → Leads",
                "Send the recap within 24 h",
                "Draft the proposal: problem, goals, scope, timeline",
                "Walk the client through it on a call",
                "On yes: duplicate the project template, book the kickoff",
            ],
            "outputs": ["lead-brief.md", "call-notes.md", "Proposal / SOW", "Kickoff agenda"],
            "exit": "Proposal accepted. Kickoff booked. Project page live.",
        },
    },
    {
        "id": "discover", "n": "01", "name": "Discover", "tag": "Research before pixels", "dd": "Diamond 1",
        "short": "Evidence, not guesses.",
        "intro": "We study your market, rivals and customers.",
        "do": ["Kickoff workshop", "Market research", "Customer interviews and surveys", "Competitor analysis", "UX audit, if you have a product", "Analytics review"],
        "get": ["Competitor analysis", "Customer insights", "UX audit report"],
        "need": ["Access to analytics and accounts", "3–5 customers to talk to", "Time for interviews"],
        "vis": "competitor",
        "team": {
            "purpose": "Know the business, the market and the users.",
            "steps": [
                "Kickoff: goals, metrics, stakeholders, limits",
                "Duplicate the project template. Research pages: Not started",
                "Collect access: analytics, hosting, domain, socials, ads",
                "Desk research: market, trends, reviews, forums",
                "Competitor Analysis page: matrix, gap, top 3 moves",
                "Interview 5 users. Record and transcribe",
                "Send a short survey when the audience is large",
                "UX audit if a product exists",
                "Start Design Inspirations: Refero and Mobbin",
                "Synthesise in Miro: themes → insights",
            ],
            "outputs": ["Competitor Analysis", "Interview notes", "ux-audit.pdf", "Design Inspirations", "Miro board"],
            "exit": "Competitor Analysis done. Insights stored in Notion.",
        },
    },
    {
        "id": "define", "n": "02", "name": "Define", "tag": "Turn research into a plan", "dd": "Diamond 1",
        "short": "A plan you approve.",
        "intro": "Research becomes strategy. You sign off before design.",
        "do": ["User personas", "User flows, every path", "Attraction strategy", "UX strategy, mobile first", "Sitemap, scope and roadmap", "Strategy brief and presentation"],
        "get": ["Personas", "User flows", "Attraction and UX strategy", "Strategy brief", "Research presentation"],
        "need": ["One review session", "Written approval"],
        "gate": "Strategy and scope sign-off",
        "vis": "userflows",
        "team": {
            "purpose": "Turn research into a plan the client signs.",
            "steps": [
                "User Personas: 3–4, with levers and how to attract each",
                "Userflows: every decision, failure and automation",
                "Attraction Strategy: sections × personas, channels",
                "UX Strategy: mobile anatomy, layout rules, trust, CTAs",
                "Sitemap and MVP scope (MoSCoW)",
                "Strategy Brief. PRD.md for build projects",
                "Build the UX Research Presentation",
                "Present. Log changes. Get written sign-off",
            ],
            "outputs": ["User Personas", "Userflows", "Attraction Strategy", "UX Strategy", "Strategy Brief", "UX Research Presentation", "PRD.md"],
            "exit": "Brief, sitemap and scope signed. New asks become change requests.",
        },
    },
    {
        "id": "design", "n": "03", "name": "Design", "tag": "Brand and experience", "dd": "Diamond 2",
        "short": "Every screen, designed.",
        "intro": "A clear identity. Every screen in Figma.",
        "do": ["2–3 design directions", "Brand system, if needed", "Wireframes", "UI for desktop and mobile", "Clickable prototype", "Design system in Storybook", "Story-led copy", "Accessibility checks"],
        "get": ["Brand system and logo files", "Wireframes", "Figma designs and prototype", "Design system"],
        "need": ["Feedback in 2–3 days per round", "Content: products, photos, reviews"],
        "gate": "Design sign-off",
        "vis": "uiux",
        "team": {
            "purpose": "Design the right solution. Hand over a system.",
            "steps": [
                "Finish Inspirations. Show 2–3 directions",
                "Branding page, when in scope (9 parts)",
                "Wireframes: one per key page",
                "Figma variables: colour, type, spacing, radius",
                "Hi-fi UI with auto layout, desktop and mobile",
                "Write UX copy from the Attraction Strategy",
                "Check contrast (WCAG AA), tap targets, layout rules",
                "Prototype the main flows. Test with 3–5 users",
                "Build components in Storybook from the tokens",
                "Handoff: Dev Mode links, DESIGN.md, assets",
            ],
            "outputs": ["Design Inspirations", "Branding", "Wireframes", "Figma file", "Prototype link", "DESIGN.md", "Storybook"],
            "exit": "Designs signed. DESIGN.md and tokens ready for build.",
        },
    },
    {
        "id": "build", "n": "04", "name": "Build", "tag": "Engineering that lasts", "dd": "Diamond 2",
        "short": "Clean code. Built to last.",
        "intro": "The right stack. Clean, secure code. A CMS you control.",
        "do": ["Architecture for your scale", "Front end, back end, database", "Payments, WhatsApp, email, CRM, AI", "A CMS you can edit", "Security from day one", "Tests on real devices", "Weekly demo on staging"],
        "get": ["Staging link", "Weekly updates", "Technical docs", "QA report"],
        "need": ["Final content and images", "Quick answers", "Testing on staging"],
        "gate": "User acceptance sign-off",
        "vis": "code",
        "team": {
            "purpose": "Ship clean, documented, secure code.",
            "steps": [
                "ARCHITECTURE.md: stack, data, roles, integrations",
                "Repo with README, CLAUDE.md and .env.example",
                "Local, staging and production environments",
                "Weekly sprints. Demo on staging every week",
                "Code review on every pull request",
                "Integrate CMS, payments, WhatsApp, email, analytics",
                "Security checklist: auth, roles, input, secrets, rate limits",
                "QA: browsers, mobile, accessibility, Lighthouse",
                "Client tests on staging (UAT). Fix. Re-test",
            ],
            "outputs": ["ARCHITECTURE.md", "CLAUDE.md", "README.md", "SECURITY.md", "QA report", "Staging URL"],
            "exit": "UAT passed. No open critical or high bugs.",
        },
    },
    {
        "id": "launch", "n": "05", "name": "Launch", "tag": "Go live and hand over",
        "short": "Live. In your name.",
        "intro": "A careful launch. Everything handed over to you.",
        "do": ["Launch checklist", "Domain, SSL and email", "SEO foundations", "Search Console and Analytics", "Redirects to keep your rankings", "CMS training"],
        "get": ["Your live product", "Handover kit", "CMS training video", "Analytics access"],
        "need": ["Domain and hosting access", "A launch date"],
        "gate": "Handover accepted",
        "vis": "launch",
        "team": {
            "purpose": "Go live. Leave the client in control.",
            "steps": [
                "Run the pre-launch checklist",
                "Deploy. Verify SSL and DNS",
                "301 redirects for redesigns",
                "Search Console: verify, submit sitemap.xml",
                "GA4 key events. Meta Pixel if ads are planned",
                "Move every account into the client’s name",
                "Record the CMS and admin walkthrough",
                "Write HANDOVER.md. Send the handover email",
                "Book a check-in two weeks out",
            ],
            "outputs": ["HANDOVER.md", "Handover email", "Training video", "GA4 + Search Console access"],
            "exit": "Client confirms access. Handover accepted.",
        },
    },
    {
        "id": "grow", "n": "06", "name": "Grow", "tag": "Automate, market, maintain",
        "short": "Make it earn.",
        "intro": "Automations, AI agents, ads, SEO and care.",
        "do": ["n8n automations", "WhatsApp agents", "Website and Telegram chatbots", "AI voice agents", "Meta ads", "SEO and content", "Updates, backups, monitoring"],
        "get": ["Monthly report", "Support channel", "Quarterly growth review"],
        "need": ["Feedback on lead quality", "Approval for campaigns"],
        "gate": "",
        "vis": "report",
        "team": {
            "purpose": "Make it pay back. Keep it healthy.",
            "steps": [
                "Monthly analytics review and report",
                "Meta ads: pixel + CAPI, audiences, creatives, weekly tuning",
                "Map manual work. Build n8n automations with alerts",
                "WhatsApp flows and templates. Get Meta approval",
                "Voice agents: build, test, review transcripts weekly",
                "Maintenance: updates, backups, uptime, patches",
                "Quarterly review: results and next moves",
            ],
            "outputs": ["Monthly report", "Automation docs", "Campaign reports", "Maintenance log"],
            "exit": "Ongoing. Each quarter ends with a review and a plan.",
        },
    },
]

PILLARS = [
    {"id": "brand", "name": "Brand & strategy", "line": "Know your market. Own your story.", "theme": "volt",
     "items": ["Market research", "Competitor analysis", "User research", "Personas", "Attraction strategy", "UX strategy", "Brand positioning", "Brand identity & logo"]},
    {"id": "design", "name": "Product design", "line": "Screens people get. And enjoy.", "theme": "violet",
     "items": ["UX audit", "User flows", "Sitemaps & wireframes", "UI design in Figma", "Design systems", "Prototypes & tests", "Landing pages"]},
    {"id": "build", "name": "Build", "line": "Software that runs for years.", "theme": "dark",
     "items": ["Websites & redesigns", "SaaS & dashboards", "ERP systems", "Online stores", "Mobile apps", "Learning platforms", "Framer & Webflow", "CMS setup"]},
    {"id": "ai", "name": "Automate & AI", "line": "Let software do the busywork.", "theme": "light",
     "items": ["n8n automations", "Email automation", "WhatsApp agents", "Website & Telegram bots", "AI voice agents", "AI in your product"]},
    {"id": "grow", "name": "Grow", "line": "Get found. Get customers. Stay healthy.", "theme": "black",
     "items": ["Meta ads", "SEO", "Search Console & Analytics", "Maintenance & support"]},
]

# The services clients can buy, each with its own route through the phases.
SERVICES = [
    {"id": "research", "name": "Research & strategy", "pillar": "brand", "vis": "research",
     "line": "Know your market before you build.",
     "goal": "Evidence for every decision, before design starts.",
     "steps": ["Kickoff workshop", "Market research", "Competitor analysis", "Customer interviews", "Personas and user flows", "Attraction and UX strategy", "Strategy brief", "Research presentation"],
     "get": "10 research documents · Strategy brief", "phases": ["discover", "define"]},
    {"id": "branding", "name": "Brand identity", "pillar": "brand", "vis": "brand",
     "line": "Be remembered. Be trusted.",
     "goal": "An identity people remember and trust.",
     "steps": ["Brand discovery workshop", "Competitor brand audit", "Positioning and story", "Logo concepts. Refine one", "Colour, type, visual language", "Brand guidelines", "Assets for web and social"],
     "get": "Logo files · Guidelines · Asset kit", "phases": ["discover", "define", "design"]},
    {"id": "audit", "name": "UX audit", "pillar": "design", "vis": "audit",
     "line": "Find what blocks your sales.",
     "goal": "Find what blocks users and sales in your product.",
     "steps": ["Agree goals and pages", "Analytics and heatmaps", "Heuristic review", "Accessibility check", "Speed and SEO scan", "Funnel review", "Rate every issue", "Report and quick wins", "Walkthrough call"],
     "get": "Audit report · Quick wins · Roadmap", "phases": ["discover", "define"]},
    {"id": "uiux", "name": "UI/UX design", "pillar": "design", "vis": "uiux",
     "line": "Screens people get. And enjoy.",
     "goal": "Every screen designed, tested and ready to build.",
     "steps": ["Design directions", "Wireframes", "UI in Figma", "Clickable prototype", "Tests with real users", "Design system in Storybook", "Developer handoff"],
     "get": "Figma designs · Prototype · Design system", "phases": ["define", "design"]},
    {"id": "landing", "name": "Landing page", "pillar": "design", "vis": "landing",
     "line": "One offer. One action.",
     "goal": "One page, one offer, one action.",
     "steps": ["Offer, audience, one CTA", "Copy first", "Wireframe", "UI in Figma", "Build: Framer, Webflow or code", "Pixel, GA4, form to CRM", "Launch and A/B tests"],
     "get": "Live page · Tracking set up", "phases": ["define", "design", "build", "launch"]},
    {"id": "website", "name": "Website & redesign", "pillar": "build", "vis": "website",
     "line": "Explain your business. Win leads.",
     "goal": "A site that explains your business and wins leads.",
     "steps": ["Audit the current site", "Keep, rewrite, remove", "Sitemap and page goals", "Wireframes, then UI", "Build with a CMS", "Redirects to keep SEO", "SEO and Analytics", "Launch and check"],
     "get": "Live site · CMS · SEO · Handover kit", "phases": ["discover", "define", "design", "build", "launch"]},
    {"id": "nocode", "name": "Framer & Webflow sites", "pillar": "build", "vis": "nocode",
     "line": "Fast sites you can edit.",
     "goal": "Fast marketing sites your team can run alone.",
     "steps": ["Pick the platform", "Design in Figma or the builder", "CMS collections", "Responsive and interactions", "SEO on every page", "Domain, forms, analytics", "Editing training"],
     "get": "Live site you can edit", "phases": ["design", "build", "launch"]},
    {"id": "saas", "name": "SaaS & dashboards", "pillar": "build", "vis": "saas",
     "line": "Role-based products that scale.",
     "goal": "Role-based products, like school or hostel systems.",
     "steps": ["Map roles and permissions", "Modules per role", "Data model and PRD", "Flows per role", "Dashboard wireframes", "Design system, then screens", "MVP in weekly sprints", "Tests with real users", "Onboarding and rollout"],
     "get": "Working MVP · Admin guide · Roadmap", "phases": ["discover", "define", "design", "build", "launch", "grow"]},
    {"id": "erp", "name": "ERP systems", "pillar": "build", "vis": "erp",
     "line": "Run operations end to end.",
     "goal": "Your operations, digital, from raw material to sale.",
     "steps": ["Map today’s process", "Design a better one", "Modules: stock, production, orders, billing, HR", "Roles, approvals, audit trail", "Data migration plan", "Roll out module by module", "Staff training"],
     "get": "ERP modules · Migration · Training", "phases": ["discover", "define", "design", "build", "launch", "grow"]},
    {"id": "store", "name": "Online stores", "pillar": "build", "vis": "store",
     "line": "Tell your story. Sell more.",
     "goal": "A store that tells your story and sells, from sarees to e-books.",
     "steps": ["Research pack", "Brand and product story", "Catalogue and filters", "Product pages that convert", "UPI, Razorpay or Stripe checkout", "Shipping or instant downloads", "WhatsApp and email updates", "Pixel, then Meta ads"],
     "get": "Live store · Delivery automation · Launch campaign", "phases": ["discover", "define", "design", "build", "launch", "grow"]},
    {"id": "lms", "name": "Learning platforms", "pillar": "build", "vis": "lms",
     "line": "Courses, tests and reports.",
     "goal": "Courses, assessments and reports for schools and colleges.",
     "steps": ["Roles: admin, teacher, student, parent", "Courses and assessments", "Moodle or custom", "Theme and branding", "Payments, video, certificates", "Enrolment and reports", "Train admins and teachers"],
     "get": "Configured LMS · Guides", "phases": ["define", "design", "build", "launch"]},
    {"id": "automation", "name": "Workflow automation", "pillar": "ai", "vis": "flow",
     "line": "Remove repetitive work.",
     "goal": "Software does the repetitive work. Your team does the rest.",
     "steps": ["Map the manual process", "Trigger, steps, outputs", "Build in n8n", "Errors, retries, alerts", "Test with real data", "Document it", "Improve monthly"],
     "get": "Running workflow · Docs", "phases": ["define", "build", "grow"]},
    {"id": "chat", "name": "WhatsApp & chat agents", "pillar": "ai", "vis": "whatsapp",
     "line": "Answer, qualify, sell. On chat.",
     "goal": "Answer, qualify and sell on WhatsApp, web and Telegram.",
     "steps": ["WhatsApp API setup (AiSensy)", "Use cases: FAQ, leads, orders", "Flows and templates", "Meta template approval", "AI knowledge and human handover", "CRM, Shopify, payments", "Opt-in and broadcasts"],
     "get": "Live agent · Templates · Flow map", "phases": ["define", "build", "grow"]},
    {"id": "voice", "name": "AI voice agents", "pillar": "ai", "vis": "voice",
     "line": "Calls answered. Bookings made.",
     "goal": "Answer calls, book appointments, qualify leads.",
     "steps": ["Pick the use case", "Script and system prompt", "Vapi or Retell, plus Twilio", "Calendar, CRM, human transfer", "Test calls and edge cases", "Consent and AI disclosure", "Launch and weekly review"],
     "get": "Live voice agent · Call reports", "phases": ["define", "build", "grow"]},
    {"id": "ads", "name": "Meta ads", "pillar": "grow", "vis": "ads",
     "line": "Paid traffic that converts.",
     "goal": "Paid traffic that turns into leads and sales.",
     "steps": ["Pixel and Conversions API", "Audience research", "Creative concepts", "Campaign and test budget", "Launch", "Weekly optimisation", "Monthly report"],
     "get": "Running campaigns · Monthly report", "phases": ["grow"]},
    {"id": "seo", "name": "SEO", "pillar": "grow", "vis": "seo",
     "line": "Get found on Google.",
     "goal": "Get found for the searches that matter.",
     "steps": ["Technical audit", "Keyword research", "On-page fixes", "Content plan", "Google Business Profile", "Search Console tracking", "Monthly report"],
     "get": "SEO plan · Fixes · Monthly report", "phases": ["launch", "grow"]},
]

# The research pack, in build order. "prompt" points at a prompt id.
RESEARCH = [
    {"id": "competitor", "name": "Competitor Analysis", "phase": "discover", "prompt": "competitor", "vis": "competitor",
     "line": "Where rivals win. The gap you own.",
     "sections": ["Rival overview", "Feature matrix ✓ ✗", "What each does best", "Strategies to borrow", "The gap you own", "Top 3 moves"],
     "example": "4 e-book platforms compared on 10 features."},
    {"id": "personas", "name": "User Personas", "phase": "define", "prompt": "personas", "vis": "personas",
     "line": "Who buys. Why. How to win them.",
     "sections": ["Archetype, role, device", "Goals and pains", "One quote, their words", "Decision levers, ranked", "How to attract them"],
     "example": "4 personas, each tied to a traffic source."},
    {"id": "userflows", "name": "Userflows", "phase": "define", "prompt": "userflows", "vis": "userflows",
     "line": "Every path. Every drop-off.",
     "sections": ["Zones: entry to repeat buy", "Every decision point", "Failure paths", "Automation steps", "Post-purchase loop"],
     "example": "8 zones, from an Instagram tap to the download."},
    {"id": "attraction", "name": "Attraction Strategy", "phase": "define", "prompt": "attraction", "vis": "attraction",
     "line": "Every section has a job.",
     "sections": ["Each section’s job", "Channel → persona", "The 8-second test", "Trust order per persona", "One move to make now"],
     "example": "8 sections mapped to 4 personas."},
    {"id": "uxstrategy", "name": "UX Strategy", "phase": "define", "prompt": "uxstrategy", "vis": "uxstrategy",
     "line": "Layout rules. Mobile first.",
     "sections": ["Mobile anatomy", "Layout rules", "Trust ladder", "CTA plan", "Speed and type"],
     "example": "375px anatomy and a 7-step trust ladder."},
    {"id": "brief", "name": "Strategy Brief", "phase": "define", "prompt": "brief", "vis": "brief",
     "line": "Two pages. One direction.",
     "sections": ["Goals and KPIs", "Audience and problem", "Positioning and story", "Experience principles", "Scope and roadmap", "Risks"],
     "example": ""},
    {"id": "presentation", "name": "UX Research Presentation", "phase": "define", "prompt": "presentation", "vis": "deck",
     "line": "The findings, walked through.",
     "sections": ["Your goal", "The rival gap", "Personas", "The key flow", "Strategy highlights", "Decisions we need"],
     "example": "Presented for the e-book store."},
    {"id": "inspiration", "name": "Design Inspirations", "phase": "design", "prompt": "direction", "vis": "inspiration",
     "line": "References that set the look.",
     "sections": ["References by section", "Source and link", "What to borrow", "2–3 directions"],
     "example": ""},
    {"id": "branding", "name": "Branding", "phase": "design", "prompt": "branding", "vis": "brand",
     "line": "A full brand system. Not just a logo.",
     "sections": ["Logo", "Colour", "Type", "Visual style", "Graphics", "Voice", "Icons", "Layout", "Mockups"],
     "example": "The same 9-part checklist on every project."},
    {"id": "wireframes", "name": "Wireframes", "phase": "design", "prompt": "wireframe", "vis": "wireframes",
     "line": "Layouts before polish.",
     "sections": ["One per key page", "Order from the UX strategy", "Real copy, no lorem", "Mobile and desktop", "States and notes"],
     "example": "Landing page and book page."},
]

DOCS = [
    ["connect", "Proposal & scope", "What, when, in which phases."],
    ["discover", "Competitor analysis", "The gap you can own."],
    ["discover", "Research findings", "What customers told us."],
    ["discover", "UX audit report", "What blocks users today."],
    ["define", "User personas", "Who buys, and why."],
    ["define", "User flows", "Every path, every drop-off."],
    ["define", "Attraction strategy", "Each section’s job."],
    ["define", "UX strategy", "Mobile-first rules."],
    ["define", "Strategy brief", "Goals and scope. Two pages."],
    ["define", "Research presentation", "Findings, for your sign-off."],
    ["design", "Brand system & logo", "Logo, colour, type, voice."],
    ["design", "Wireframes", "Key pages, agreed early."],
    ["design", "Figma designs & prototype", "Every screen. Clickable."],
    ["design", "Design system", "Reusable components."],
    ["build", "Weekly updates & staging", "Progress every week."],
    ["build", "Technical docs", "Any developer can maintain it."],
    ["build", "QA report", "Tested on real devices."],
    ["launch", "Live product", "Deployed and secured."],
    ["launch", "Handover kit", "Code and accounts. Your name."],
    ["launch", "CMS training video", "Edit content yourself."],
    ["grow", "Monthly report", "Traffic, leads, sales. Next steps."],
]

COMPARE = [
    ["Explain your business five times", "Explain it once"],
    ["Design and code drift apart", "One design system, end to end"],
    ["Site, ads and automations built apart", "Planned to work together"],
    ["Nobody owns the result", "We track your goals"],
    ["Support ends at delivery", "We stay after launch"],
]

TOGETHER = [
    ["One point of contact", "One lead. One chat. Always."],
    ["Weekly updates", "Done, next, needed. Every week."],
    ["Shared workspace", "Notion, Figma, staging. Look any time."],
    ["Your OK at every gate", "Nothing moves without your sign-off."],
    ["Clear change process", "New idea? We estimate. You decide."],
    ["You own everything", "Code, designs, accounts. Your name."],
]

PRINCIPLES = [
    ["Your story first", "Your founder story, carried to every screen."],
    ["Research before pixels", "Every design decision has a reason."],
    ["A proven process", "Double Diamond. Weekly sprints. Checklists."],
    ["Built to last", "Clean code. Documented. Secure."],
    ["Ideas beyond the brief", "We suggest what helps your goals."],
    ["A long-term partner", "We earn your next phase on this one."],
]

WORK = [
    {"kind": "SaaS · Dashboards", "name": "Institution management systems", "line": "Hostel, school, college and university platforms. Role-based dashboards.", "vis": "saas"},
    {"kind": "Learning", "name": "Learning management systems", "line": "Course platforms for colleges and schools. Custom and Moodle.", "vis": "lms"},
    {"kind": "ERP", "name": "ERP for a handloom saree house", "line": "Production software, from yarn to orders.", "vis": "erp"},
    {"kind": "Brand · Web", "name": "Story-led saree website", "line": "The weavers’ story, told online. E-commerce next.", "vis": "saree"},
]

# Team playbook: short notes for the starter tool stack. "core" marks the simple everyday set.
TOOL_NOTES = {
    "Notion": ("Our knowledge base: leads, projects, research", True),
    "Miro": ("Affinity maps, journeys, workshops", False),
    "FigJam": ("User flows and sitemaps with clients", False),
    "Google Forms": ("Questionnaires and surveys", False),
    "Claude": ("Research, synthesis, briefs, docs", True),
    "Microsoft Clarity": ("Heatmaps and recordings for audits", False),
    "PageSpeed Insights": ("Speed and Core Web Vitals", False),
    "Refero": ("Real screens and flows. Styles as DESIGN.md", False),
    "Mobbin": ("App and web patterns, searchable", False),
    "Toolfolio": ("Directory of design, AI and no-code tools", False),
    "Laws of UX": ("UX laws to explain design decisions", False),
    "WebAIM Contrast Checker": ("WCAG contrast checks", False),
    "Figma": ("UI, variables, prototypes, Dev Mode", True),
    "Storybook": ("Component library and docs", False),
    "Claude Code": ("Build, refactor and review code", True),
    "GitHub": ("Repos, pull requests, reviews", True),
    "Framer": ("No-code sites with CMS", True),
    "Webflow": ("No-code sites for content-heavy clients", False),
    "Moodle": ("LMS for colleges and schools", False),
    "Vercel": ("Hosting, preview links, production", True),
    "Razorpay": ("Payments and UPI. Webhooks into n8n", True),
    "n8n": ("Workflows: leads, emails, reports, AI steps", True),
    "AiSensy": ("WhatsApp API: broadcasts, bots, agents", True),
    "Telegram Bot API": ("Telegram chatbots", False),
    "Twilio": ("Numbers and calling for voice agents", False),
    "Vapi": ("Voice agents. More control", False),
    "Retell AI": ("Voice agents. Faster setup", False),
    "Claude API": ("AI features inside client products", False),
    "Meta Ads Manager": ("Facebook and Instagram campaigns", False),
    "Google Search Console": ("Indexing, sitemaps, search data", True),
    "Google Analytics 4": ("Traffic, sources, conversions", True),
    "UI UX Pro Max": ("Design knowledge for Claude Code", False),
    "frontend-design": ("Anthropic skill for distinctive front ends", False),
    "Vercel deploy": ("Lets Claude Code deploy to Vercel", False),
    "Refero MCP": ("Refero screens inside Claude Code (Pro plan)", False),
    "Figma MCP": ("Figma frames and tokens inside Claude Code", False),
    "skill-creator": ("Turn our SOPs into Claude skills", False),
}

# Team playbook: starter knowledge base (Notion workspace, repo docs kit, research properties).
KB = [
    {"id": "leads", "title": "Leads", "type": "Doc", "tags": ["notion", "database"], "note": "Status, source, services wanted, call date, proposal link."},
    {"id": "projects", "title": "Projects", "type": "Doc", "tags": ["notion", "database"], "note": "Client, type, current phase, owner."},
    {"id": "project-template", "title": "Project template", "type": "Template", "tags": ["notion"], "note": "Duplicate per client. Cover and icon per client."},
    {"id": "user-research", "title": "User Research gallery", "type": "Doc", "tags": ["notion", "research"], "note": "One page per research doc. Status: Not started → Done."},
    {"id": "inspiration", "title": "Inspiration library", "type": "Doc", "tags": ["notion", "design"], "note": "Shared across projects: screenshot, source, pattern, industry."},
    {"id": "templates", "title": "Templates", "type": "Template", "tags": ["notion"], "note": "Research pages, questionnaire, proposal, audit report, handover email."},
    {"id": "prompt-library", "title": "Prompt & skill library", "type": "Doc", "tags": ["notion", "ai"], "note": "Mirror of the prompts. Note what worked."},
    {"id": "tool-stack", "title": "Tool stack", "type": "Doc", "tags": ["notion"], "note": "Tool, use, cost, login owner."},
    {"id": "research-props", "title": "User Research properties", "type": "Note", "tags": ["notion", "research"], "note": "Add: Phase, Owner, Client-visible, Due date, Last reviewed, Prompt used."},
    {"id": "readme", "title": "README.md", "type": "Template", "tags": ["repo"], "note": "Install, run, deploy."},
    {"id": "claude-md", "title": "CLAUDE.md", "type": "Template", "tags": ["repo", "ai"], "note": "Rules and context for Claude Code."},
    {"id": "prd", "title": "PRD.md", "type": "Template", "tags": ["repo"], "note": "Features, user stories, acceptance criteria."},
    {"id": "architecture", "title": "ARCHITECTURE.md", "type": "Template", "tags": ["repo"], "note": "Stack, data model, roles, integrations."},
    {"id": "design-md", "title": "DESIGN.md", "type": "Template", "tags": ["repo", "design"], "note": "Tokens, components, design rules."},
    {"id": "security", "title": "SECURITY.md", "type": "Template", "tags": ["repo"], "note": "Auth, data handling, checklist results."},
    {"id": "handover", "title": "HANDOVER.md", "type": "Template", "tags": ["repo"], "note": "Accounts, access, support plan."},
    {"id": "changelog", "title": "CHANGELOG.md", "type": "Template", "tags": ["repo"], "note": "What changed and when."},
]
